"""OFSC Python Wrapper v3.0 Models

This module provides backward-compatible imports for all Pydantic models used
throughout the OFSC Python Wrapper. Models are now organized into focused
submodules but can still be imported from this root module.

Usage:
    # These imports continue to work unchanged from v2
    from ofsc.models import Property, Workskill, Activity
    from ofsc.models import OFSConfig, OFSResponseList
    
    # New submodule imports are also available
    from ofsc.models.metadata import Property
    from ofsc.models.core import Activity  
    from ofsc.models.capacity import CapacityArea
"""

# Base models and infrastructure
from .base import (
    BaseOFSResponse,
    CsvList,
    EntityEnum,
    OFSResponseList,
    SharingEnum,
    Translation,
    TranslationList,
)

# Authentication and configuration models
from .auth import (
    OFSApi,
    OFSAPIError,
    OFSConfig,
    OFSOAuthRequest,
)

# Metadata API models
from .metadata import (
    ActivityType,
    ActivityTypeColors,
    ActivityTypeFeatures,
    ActivityTypeGroup,
    ActivityTypeGroupListResponse,
    ActivityTypeListResponse,
    ActivityTypeTimeSlots,
    Application,
    ApplicationListResponse,
    ApplicationsResourcestoAllow,
    Condition,
    EnumerationValue,
    EnumerationValueList,
    InventoryType,
    InventoryTypeListResponse,
    Link,
    Organization,
    OrganizationListResponse,
    Property,
    PropertyListResponse,
    ResourceType,
    ResourceTypeListResponse,
    TimeSlot,
    TimeSlotListResponse,
    WorkSkillGroup,
    WorkSkillGroupListResponse,
    Workskill,
    WorkskillCondition,
    WorkskillConditionListResponse,
    WorkskillListResponse,
    Workzone,
    WorkzoneListResponse,
    WorksSkillAssignments,
)

# Core API models
from .core import (
    Activity,
    ActivityKeys,
    AssignedLocation,
    AssignedLocationsRequest,
    AssignedLocationsResponse,
    BaseUser,
    BulkUpdateActivityItem,
    BulkUpdateError,
    BulkUpdateParameters,
    BulkUpdateRequest,
    BulkUpdateResult,
    BulkUpdateResponse,
    BulkUpdateWarning,
    CalendarView,
    CalendarViewItem,
    CalendarViewItemRecordType,
    CalendarViewList,
    CalendarViewShift,
    DailyExtractFiles,
    DailyExtractFolders,
    DailyExtractItem,
    DailyExtractItemList,
    GetActivityRequest,
    Link as CoreLink,
    Location,
    LocationListResponse,
    Recurrence,
    RecurrenceType,
    Resource,
    ResourcePosition,
    ResourcePositionListResponse,
    ResourceUsersListResponse,
    ResourceWorkScheduleItem,
    ResourceWorkScheduleResponse,
    Subscription,
    SubscriptionList,
    User,
    UserListResponse,
    WeekDay,
)

# Capacity API models  
from .capacity import (
    CapacityArea,
    CapacityAreaConfiguration,
    CapacityAreaListResponse,
    CapacityAreaParent,
    CapacityAreaResponseItem,
    CapacityCategory,
    CapacityCategoryItem,
    CapacityCategoryListResponse,
    CapacityMetrics,
    CapacityRequest,
    CapacityResponseItem,
    GetCapacityResponse,
    GetQuotaRequest,
    GetQuotaResponse,
    Item,
    ItemList,
    QuotaAreaItem,
    QuotaCategoryItem,
    QuotaResponseItem,
    QuotaTimeInterval,
)

# Ensure all exports are available
__all__ = [
    # Base models
    "BaseOFSResponse",
    "CsvList",
    "EntityEnum", 
    "OFSResponseList",
    "SharingEnum",
    "Translation",
    "TranslationList",
    
    # Auth models
    "OFSApi",
    "OFSAPIError", 
    "OFSConfig",
    "OFSOAuthRequest",
    
    # Metadata models
    "ActivityType",
    "ActivityTypeColors",
    "ActivityTypeFeatures", 
    "ActivityTypeGroup",
    "ActivityTypeGroupListResponse",
    "ActivityTypeListResponse",
    "ActivityTypeTimeSlots",
    "Application",
    "ApplicationListResponse",
    "ApplicationsResourcestoAllow",
    "Condition",
    "EnumerationValue",
    "EnumerationValueList",
    "InventoryType",
    "InventoryTypeListResponse",
    "Link",
    "Organization",
    "OrganizationListResponse",
    "Property",
    "PropertyListResponse",
    "ResourceType",
    "ResourceTypeListResponse",
    "TimeSlot",
    "TimeSlotListResponse",
    "WorkSkillGroup",
    "WorkSkillGroupListResponse",
    "Workskill",
    "WorkskillCondition",
    "WorkskillConditionListResponse",
    "WorkskillListResponse",
    "Workzone",
    "WorkzoneListResponse",
    "WorksSkillAssignments",
    
    # Core models
    "Activity",
    "ActivityKeys",
    "AssignedLocation",
    "AssignedLocationsRequest",
    "AssignedLocationsResponse",
    "BaseUser",
    "BulkUpdateActivityItem",
    "BulkUpdateError",
    "BulkUpdateParameters",
    "BulkUpdateRequest",
    "BulkUpdateResult",
    "BulkUpdateResponse",
    "BulkUpdateWarning",
    "CalendarView",
    "CalendarViewItem",
    "CalendarViewItemRecordType",
    "CalendarViewList",
    "CalendarViewShift",
    "DailyExtractFiles",
    "DailyExtractFolders",
    "DailyExtractItem",
    "DailyExtractItemList",
    "GetActivityRequest",
    "CoreLink",
    "Location",
    "LocationListResponse",
    "Recurrence",
    "RecurrenceType",
    "Resource",
    "ResourcePosition",
    "ResourcePositionListResponse",
    "ResourceUsersListResponse",
    "ResourceWorkScheduleItem",
    "ResourceWorkScheduleResponse",
    "Subscription",
    "SubscriptionList",
    "User",
    "UserListResponse",
    "WeekDay",
    
    # Capacity models
    "CapacityArea",
    "CapacityAreaConfiguration",
    "CapacityAreaListResponse",
    "CapacityAreaParent",
    "CapacityAreaResponseItem",
    "CapacityCategory",
    "CapacityCategoryItem",
    "CapacityCategoryListResponse", 
    "CapacityMetrics",
    "CapacityRequest",
    "CapacityResponseItem",
    "GetCapacityResponse",
    "GetQuotaRequest",
    "GetQuotaResponse",
    "Item",
    "ItemList",
    "QuotaAreaItem",
    "QuotaCategoryItem",
    "QuotaResponseItem",
    "QuotaTimeInterval",
]