"""OFSC Python Wrapper v3.0 Models

This module provides backward-compatible imports for all Pydantic models used
throughout the OFSC Python Wrapper. Models are now organized into focused
submodules but can still be imported from this root module.

Usage:
    # These imports continue to work unchanged from v2
    from ofsc.models import Property, Workskill, Activity
    from ofsc.models import OFSConfig, OFSResponseList

    # New submodule imports are also available
    from ofsc.models.metadata import PropertyResponse as Property
    from ofsc.models.core import Activity
    from ofsc.models.capacity import CapacityArea
"""

# Base models and infrastructure
# Authentication and configuration models
from .auth import (
    OFSApi,
    OFSAPIError,
    OFSConfig,
    OFSOAuthRequest,
)
from .base import (
    BaseOFSResponse,
    CsvList,
    EntityEnum,
    OFSResponseList,
    SharingEnum,
    Translation,
    TranslationList,
)

# Capacity API models
from .capacity import (
    CapacityArea,
    CapacityAreaConfiguration,
    CapacityAreaListResponse,
    CapacityAreaParent,
    CapacityAreaResponseItem,
    CapacityCategoryItem,
    CapacityCategoryListResponse,
    CapacityCategoryRequest,
    CapacityCategoryResponse,
    CapacityMetrics,
    CapacityRequest,
    CapacityResponseItem,
    GetCapacityResponse,
    GetQuotaRequest,
    GetQuotaResponse,
    Item,
    ItemList,
    QuotaAreaItem,
    QuotaCategoryItem,
    QuotaResponseItem,
    QuotaTimeInterval,
)

# Core API models
from .core import (
    Activity,
    ActivityCapacityCategory,
    ActivityCapacityCategoryListResponse,
    ActivityCustomerInventory,
    ActivityCustomerInventoryListResponse,
    ActivityDeinstalledInventory,
    ActivityDeinstalledInventoryListResponse,
    ActivityInstalledInventory,
    ActivityInstalledInventoryListResponse,
    ActivityKeys,
    ActivityLink,
    ActivityLinkListResponse,
    ActivityListResponse,
    ActivityMoveRequest,
    ActivityMoveResponse,
    ActivityMultidaySegment,
    ActivityMultidaySegmentListResponse,
    ActivityProperty,
    ActivityRequiredInventory,
    ActivityRequiredInventoryListResponse,
    ActivityResourcePreference,
    ActivityResourcePreferenceListResponse,
    ActivitySubmittedForm,
    ActivitySubmittedFormListResponse,
    AssignedLocation,
    AssignedLocationsRequest,
    AssignedLocationsResponse,
    BaseUser,
    BulkInventoryUpdateItem,
    BulkInventoryUpdateRequest,
    BulkInventoryUpdateResponse,
    BulkScheduleUpdateItem,
    BulkScheduleUpdateRequest,
    BulkScheduleUpdateResponse,
    BulkSkillUpdateItem,
    BulkSkillUpdateRequest,
    BulkSkillUpdateResponse,
    BulkUpdateActivityItem,
    BulkUpdateError,
    BulkUpdateParameters,
    BulkUpdateRequest,
    BulkUpdateResponse,
    BulkUpdateResult,
    BulkUpdateWarning,
    BulkZoneUpdateItem,
    BulkZoneUpdateRequest,
    BulkZoneUpdateResponse,
    CalendarItem,
    CalendarListResponse,
    CalendarView,
    CalendarViewItem,
    CalendarViewItemRecordType,
    CalendarViewList,
    CalendarViewShift,
    DailyExtractFiles,
    DailyExtractFolders,
    DailyExtractItem,
    DailyExtractItemList,
    GetActivityRequest,
    Inventory,
    InventoryListResponse,
    LastKnownPosition,
    LastKnownPositionListResponse,
    Location,
    LocationListResponse,
    NearbyActivity,
    NearbyActivityListResponse,
    PositionHistory,
    PositionHistoryItem,
    Recurrence,
    RecurrenceType,
    Resource,
    ResourceInventory,
    ResourceInventoryListResponse,
    ResourceListResponse,
    ResourceLocationRequest,
    ResourceMatchRequest,
    ResourceMatchResponse,
    ResourcePlan,
    ResourcePlanListResponse,
    ResourcePosition,
    ResourcePositionListResponse,
    ResourcePropertyRequest,
    ResourcePropertyValue,
    ResourcesInAreaQuery,
    ResourcesInAreaResponse,
    ResourceUsersListResponse,
    ResourceWorkScheduleItem,
    ResourceWorkScheduleItemListResponse,
    ResourceWorkSkill,
    ResourceWorkSkillListResponse,
    ResourceWorkZone,
    ResourceWorkZoneListResponse,
    RouteActivationRequest,
    RouteActivationResponse,
    RouteInfoListResponse,
    ServiceRequest,
    ServiceRequestListResponse,
    ServiceRequestProperty,
    SetPositionsRequest,
    SetPositionsResponse,
    Subscription,
    SubscriptionList,
    UrgentAssignmentRequest,
    UrgentAssignmentResponse,
    User,
    UserListResponse,
    WeekDay,
    WorkScheduleRequest,
)
from .core import (
    Link as CoreLink,
)

# Metadata API models
from .metadata import (
    ActivityType,
    ActivityTypeColors,
    ActivityTypeFeatures,
    ActivityTypeGroup,
    ActivityTypeGroupListResponse,
    ActivityTypeListResponse,
    ActivityTypeTimeSlots,
    Application,
    ApplicationListResponse,
    ApplicationsResourcestoAllow,
    Condition,
    EnumerationValue,
    EnumerationValueList,
    InventoryType,
    InventoryTypeListResponse,
    Link,
    Organization,
    OrganizationListResponse,
    PropertyListResponse,
    PropertyRequest,
    PropertyResponse,
    ResourceType,
    ResourceTypeListResponse,
    TimeSlot,
    TimeSlotListResponse,
    Workskill,
    WorkskillCondition,
    WorkskillConditionListResponse,
    WorkSkillGroup,
    WorkSkillGroupListResponse,
    WorkskillListResponse,
    WorksSkillAssignments,
    Workzone,
    WorkzoneListResponse,
)

# Backward compatibility alias
Property = PropertyResponse

# Ensure all exports are available
__all__ = [
    # Base models
    "BaseOFSResponse",
    "CsvList",
    "EntityEnum",
    "OFSResponseList",
    "SharingEnum",
    "Translation",
    "TranslationList",
    # Auth models
    "OFSApi",
    "OFSAPIError",
    "OFSConfig",
    "OFSOAuthRequest",
    # Metadata models
    "ActivityType",
    "ActivityTypeColors",
    "ActivityTypeFeatures",
    "ActivityTypeGroup",
    "ActivityTypeGroupListResponse",
    "ActivityTypeListResponse",
    "ActivityTypeTimeSlots",
    "Application",
    "ApplicationListResponse",
    "ApplicationsResourcestoAllow",
    "Condition",
    "EnumerationValue",
    "EnumerationValueList",
    "InventoryType",
    "InventoryTypeListResponse",
    "Link",
    "Organization",
    "OrganizationListResponse",
    "Property",  # Backward compatibility alias for PropertyResponse
    "PropertyRequest",
    "PropertyResponse",
    "PropertyListResponse",
    "ResourceType",
    "ResourceTypeListResponse",
    "TimeSlot",
    "TimeSlotListResponse",
    "WorkSkillGroup",
    "WorkSkillGroupListResponse",
    "Workskill",
    "WorkskillCondition",
    "WorkskillConditionListResponse",
    "WorkskillListResponse",
    "Workzone",
    "WorkzoneListResponse",
    "WorksSkillAssignments",
    # Core models
    "Activity",
    "ActivityCapacityCategory",
    "ActivityCapacityCategoryListResponse",
    "ActivityCustomerInventory",
    "ActivityCustomerInventoryListResponse",
    "ActivityDeinstalledInventory",
    "ActivityDeinstalledInventoryListResponse",
    "ActivityInstalledInventory",
    "ActivityInstalledInventoryListResponse",
    "ActivityKeys",
    "ActivityLink",
    "ActivityLinkListResponse",
    "ActivityListResponse",
    "ActivityMoveRequest",
    "ActivityMoveResponse",
    "ActivityMultidaySegment",
    "ActivityMultidaySegmentListResponse",
    "ActivityProperty",
    "ActivityRequiredInventory",
    "ActivityRequiredInventoryListResponse",
    "ActivityResourcePreference",
    "ActivityResourcePreferenceListResponse",
    "ActivitySubmittedForm",
    "ActivitySubmittedFormListResponse",
    "AssignedLocation",
    "AssignedLocationsRequest",
    "AssignedLocationsResponse",
    "BaseUser",
    "BulkUpdateActivityItem",
    "BulkUpdateError",
    "BulkUpdateParameters",
    "BulkUpdateRequest",
    "BulkUpdateResult",
    "BulkUpdateResponse",
    "BulkUpdateWarning",
    "BulkInventoryUpdateItem",
    "BulkInventoryUpdateRequest",
    "BulkInventoryUpdateResponse",
    "BulkScheduleUpdateItem",
    "BulkScheduleUpdateRequest",
    "BulkScheduleUpdateResponse",
    "BulkSkillUpdateItem",
    "BulkSkillUpdateRequest",
    "BulkSkillUpdateResponse",
    "BulkZoneUpdateItem",
    "BulkZoneUpdateRequest",
    "BulkZoneUpdateResponse",
    "CalendarItem",
    "CalendarListResponse",
    "CalendarView",
    "CalendarViewItem",
    "CalendarViewItemRecordType",
    "CalendarViewList",
    "CalendarViewShift",
    "DailyExtractFiles",
    "DailyExtractFolders",
    "DailyExtractItem",
    "DailyExtractItemList",
    "GetActivityRequest",
    "Inventory",
    "InventoryListResponse",
    "LastKnownPosition",
    "LastKnownPositionListResponse",
    "CoreLink",
    "Location",
    "LocationListResponse",
    "NearbyActivity",
    "NearbyActivityListResponse",
    "PositionHistory",
    "PositionHistoryItem",
    "Recurrence",
    "RecurrenceType",
    "Resource",
    "ResourceInventory",
    "ResourceInventoryListResponse",
    "ResourceListResponse",
    "ResourceLocationRequest",
    "ResourceMatchRequest",
    "ResourceMatchResponse",
    "ResourcePlan",
    "ResourcePlanListResponse",
    "ResourcePosition",
    "ResourcePositionListResponse",
    "ResourcePropertyRequest",
    "ResourcePropertyValue",
    "ResourcesInAreaQuery",
    "ResourcesInAreaResponse",
    "ResourceUsersListResponse",
    "ResourceWorkScheduleItem",
    "ResourceWorkScheduleItemListResponse",
    "ResourceWorkSkill",
    "ResourceWorkSkillListResponse",
    "ResourceWorkZone",
    "ResourceWorkZoneListResponse",
    "RouteActivationRequest",
    "RouteActivationResponse",
    "RouteInfoListResponse",
    "ServiceRequest",
    "ServiceRequestListResponse",
    "ServiceRequestProperty",
    "SetPositionsRequest",
    "SetPositionsResponse",
    "Subscription",
    "SubscriptionList",
    "UrgentAssignmentRequest",
    "UrgentAssignmentResponse",
    "User",
    "UserListResponse",
    "WeekDay",
    "WorkScheduleRequest",
    # Capacity models
    "CapacityArea",
    "CapacityAreaConfiguration",
    "CapacityAreaListResponse",
    "CapacityAreaParent",
    "CapacityAreaResponseItem",
    "CapacityCategoryRequest",
    "CapacityCategoryResponse",
    "CapacityCategoryItem",
    "CapacityCategoryListResponse",
    "CapacityMetrics",
    "CapacityRequest",
    "CapacityResponseItem",
    "GetCapacityResponse",
    "GetQuotaRequest",
    "GetQuotaResponse",
    "Item",
    "ItemList",
    "QuotaAreaItem",
    "QuotaCategoryItem",
    "QuotaResponseItem",
    "QuotaTimeInterval",
]
