name: Python package published via poetry
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to testpypi
        uses: JRubics/poetry-publish@v1.12
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          repository_name: "ofsc_test"
          repository_url: "https://test.pypi.org/legacy/"
